# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-12 10:22
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180511_1047'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_delete_fansfollows'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('note', DjangoUeditor.models.UEditorField(blank=True, default='', null=True, verbose_name='笔记')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Video', verbose_name='视频id')),
            ],
            options={
                'verbose_name': '同学笔记',
                'verbose_name_plural': '同学笔记',
            },
        ),
    ]
