# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-16 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20180411_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCourse',
            fields=[
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
        migrations.CreateModel(
            name='FigthCourse',
            fields=[
            ],
            options={
                'verbose_name': '实战课程',
                'verbose_name_plural': '实战课程',
                'proxy': True,
                'indexes': [],
            },
            bases=('courses.course',),
        ),
    ]
