# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_courseprogess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseprogess',
            name='progess',
            field=models.FloatField(default=0, verbose_name='当前学习时间'),
        ),
    ]
