# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-11 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20180511_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.FloatField(default=0, verbose_name='学习时长(分钟数)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='learn_times',
            field=models.FloatField(default=0, verbose_name='视频时长(分钟数)'),
        ),
    ]
