# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-04-15 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180414_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nick_name',
            field=models.CharField(default='个人中心', max_length=50, verbose_name='昵称'),
        ),
    ]
